include:
  - local: ci/gitlab_templates/JOB_TEMPLATE.yml
  - local: ci/gitlab_templates/RULES.yml

variables:
  DEFAULT_ROS_DISTROS: humble
  STABLE_BRANCH: main

.common:
  tags: &kaniko_runner
    - intranet

precommit:
  tags: *kaniko_runner
  stage: format
  extends:
    - .precommit
    - .on_default_merge_event

build:
  tags: *kaniko_runner
  stage: build
  extends:
    - .build_with_kaniko
  variables:
    NAME: ur5e_cell_${DEFAULT_ROS_DISTRO}
    FOLDER: ""
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

publish:
  tags: *kaniko_runner
  stage: publish
  extends:
    - .publish
    - .on_default_merge_tag
  variables:
    NAME: ur5e_cell_${DEFAULT_ROS_DISTRO}

stages:
  - format
  - build
  - publish
